### ISSUE TITLE
Tetragrammaton broken if "Enable Queue Adjustments" enabled

### ISSUE THREAD

**Issue by Beetle-Lord** [UnknownX7/ReAction#128]
Per the title, the WHM ability "Tetragrammaton" does not work properly if "Enable Queue Adjustments" is enabled.

First off, Tetragrammaton cannot ever be queued if "Enable Queue Adjustments" is enabled. This makes it super clunky to cast.

Secondly, if "Enable Queue Adjustments" is enabled AND Tetagrammaton is being used in a Stack AND "Fail if On Cooldown" is enabled for that stack AND you are in combat, Tetagrammaton cannot be cast at all. It just stops working.

**Comment by frailfangs** [comment]
I want to add onto this, the skills Drill and Bioblaster on Machinist also are unable to be queued, and the skill Living Muse on Pictomancer as well. Seeing the problem is common on Tetragrammaton makes me think that perhaps ReAction is struggling with skills that later gain extra charges. Unsure if this is the reason why, but judging by the fact these skills all share this in common, I would not be surprised if that's the root of the issue. I don't know how the plugin functions on the backend which might cause this, but I wanted to add onto this comment as this has been affecting play quite a bit.
