### ISSUE TITLE
A doubt

### ISSUE THREAD

**Issue by Alkeyd** [UnknownX7/ReAction#18]
I don't know what the "Enable FPS Alignment" option should or should do, could someone explain to me what it is for?

**Comment by UnknownX7** [comment]
Practically nullifies the effects of FPS on GCD or animation lock by delaying the final cooldown frame slightly in order to align it with the point in time that they would finish their cooldowns. It's less valuable the higher your FPS, but it does still raise the chance that you can hit one final GCD and prevents drifting.
