### ISSUE TITLE
Detectable by server?

### ISSUE THREAD

**Issue by jtabox** [UnknownX7/ReAction#28]
Hey, not really an issue or suggestion, mostly a question. I apologize for asking here, but haven't found where else to. Anyway, I'm wondering how possible it is that the server detects I'm using an addon when I activate some of the "Other Settings". For example auto dismount when using an action or auto targeting. Asking because those do not follow the "1 keypress = 1 action"-rule any more, since the addon sends 2 actions to the server with almost no interval. I'm loving the addon and its functionality but was mostly wondering.

**Comment by UnknownX7** [comment]
Short answer: Yes, but extremely unlikely.

Long answer:
Most things in "Other Settings" do alter something that the server could see. However, they don't alter it in a way they could see reliably. For auto dismount in particular, they could check the time between your dismount and action, but they would have to account for latency and would likely catch normal players occasionally. Additionally, stacks in both ReAction and MOAction remove the need for changing targets, which is also something sent to the server.

However, you should also know that this is true for most plugins if SE wants to put in the effort. Most plugins will slightly change someone's behavior or some data that the server eventually receives. Additionally, even if something is fully clientside, it would not be impossible for them to detect it in a future update, but due to the number of people using plugins, I doubt they would do this without explicitly announcing it since it would result in a lot of lost revenue.
