### ISSUE TITLE
[Bug? Maybe?] 'Ground Target Queueing' does not queue the chosen location.

### ISSUE THREAD

**Issue by ghost** [UnknownX7/ReAction#60]
It instead attempts to find the location when the queued ground target action is actually executed. This is inconsistent with other queuing behaviors that queue their original target when the action was first queued.

**Comment by chckxy** [comment]
@UnknownX7 could you look into this? when queued between gcds, the placed asylum/bell will be directly under the target and not where your mouse is. i believe this is what's causing asylum/bell to be placed under the boss for p10 (i.e. not where the party is), which makes this setting unusable.

**Comment by UnknownX7** [comment]
> @UnknownX7 could you look into this? when queued between gcds, the placed asylum/bell will be directly under the target and not where your mouse is. i believe this is what's causing asylum/bell to be placed under the boss for p10 (i.e. not where the party is), which makes this setting unusable.

This setting shouldn't be causing any placement issues, the only time ReAction will set a location is if the ground target is in a stack. I have heard of this bug in the past though, but it was caused by Redirect. I'm not sure of whether or not it was fixed.

As for not queuing the location, I'm aware of it, but the game doesn't support queuing coordinates and plugins can force things to be placed in invalid locations, so fixing it is a bit more in-depth than just overriding the location.

**Comment by chckxy** [comment]
oh yep, it is definitely Redirect. turning off queueing in ReAction fixes it, but so does turning on the cursor setting in Redirect. thanks ❤️
