### ISSUE TITLE
[Bug] Camera Relative Dashes doesn't work in PVP

### ISSUE THREAD

**Issue by DenL** [UnknownX7/ReAction#63]
Hi, I have noticed that Camera Relative Dashes does not work in PVP (or in wolves den pier)  for DRG's Elusive Jump. Perhaps this feature is ability based? Any chance to add pvp abilities to it?

Thanks!

**Comment by xterion** [comment]
I dont think this is a bug in ReAction itself, but because Dalamud disables plugins in PVP to prevent ppl getting unfair advantages. 

Camera relative dashes would probably make it hard for enemies to track you since the server displays you dashing somewhere completely else and then porting you after you arrive to your actual position, at least thats what ist looks like in raids for other ppl.
