### ISSUE TITLE
SMN demi bahamut and phoenix won't summon

### ISSUE THREAD

**Issue by IzanaghiOkami** [UnknownX7/ReAction#76]
after the recent update, very frequently my demi's won't summon when off cd and by all accounts ready to summon. I'll spam them multiple times until it works after like 6 seconds. attached an example from p8sp2 
![ApplicationFrameHost_sCd8oDo1OB](https://user-images.githubusercontent.com/125611148/219494488-99227fd5-a5c1-4222-b0ad-3f11d4dc0d47.gif)

**Comment by redrobe9** [comment]
To add some additional context. This happens when "Enhanced Auto Face Target" is enabled and you aren't facing the target. Seems that it's suddenly being recognized as an action that fits under the criteria. If you turn off the in-game auto face target it does not fix the issue so I would recommend turning the Enhanced setting off for the time being.

**Comment by IzanaghiOkami** [comment]
Thank you for the response ^^
